migtools/lib-ui

.github/pull_request_template.md, .releaserc, README.md
Also adds a pull request template that will explain how to trigger releases when opening a pull request.
=> build(.releaserc): add .releaserc to trigger releases from more commit types

.github/pull_request_template.md, src/components/StatusIcon/StatusIcon.tsx
Already found an issue when trying to use StatusIcon in mig-ui. Also snuck in a tweak to the PR template now that I can see it in action.
=> fix(statusicon): add support for ReactNode labels instead of strings

README.md, package.json, src/hooks/useSelectionState/index.ts, src/hooks/useSelectionState/useSelectionState.stories.mdx, src/hooks/useSelectionState/useSelectionState.stories.tsx, src/hooks/useSelectionState/useSelectionState.test.ts, src/hooks/useSelectionState/useSelectionState.ts, src/index.ts, yarn.lock
Adding one of the custom hooks I introduced in virt-ui, so I can mess with the usage of hooks in Storybook stories.
Turns out you can't use TypeScript directly in an MDX file, but Storybook supports importing the body of a story from another file.
I'll leave the rest of #12 for another day so I can get back to working on virt-ui.
=> feat(useselectionstate): add useSelectionState hook, stories and test stubs

src/hooks/useSelectionState/useSelectionState.stories.mdx, src/hooks/useSelectionState/useSelectionState.stories.tsx, src/hooks/useSelectionState/useSelectionState.ts
@ibolton336 @gildub do you mind merging this ahead of my wizard state PR for virt-ui? I need it to manage the form state for the filter VMs tree without duplicating the logic from useSelectionState.
This just adds the ability to pass in the `[value, setValue]` array from outside the hook instead of using the `React.useState` that is called inside the hook, so we can get all the fancy useSelectionState logic but store the value inside useFormState and validate it.
=> feat(useselectionstate): add support for externally lifted state

README.md, package.json
Currently `axios` is both installed as a real dependency and listed as a `peerDependency` the consumer must install themselves. I only intended the latter (because it is included in rollup's `peerDepsExternal` plugin, it doesn't actually need to be bundled).
It is still needed at build time for TS types and such, so this moves it into `devDependencies`.
=> fix(package.json): treat axios properly as an external peer dependency

src/components/ValidatedTextInput/ValidatedTextInput.tsx, src/hooks/useFormState/useFormState.stories.mdx, src/hooks/useFormState/useFormState.ts
Repeats changes from https://github.com/konveyor/virt-ui/pull/124, to support conditional validation schema in useFormState and non-required text fields in ValidatedTextInput.
=> fix(useformstate): don't memoize schema (so it can be conditional), allow non-required text fields

README.md, package.json
According to https://blog.jim-nielsen.com/2018/installing-and-building-an-npm-package-from-github/, if our package has a `prepare` script that runs the build, we can install unreleased branches of it temporarily in WIP app PRs by using `github:konveyor/lib-ui#some-branch` or `github:mturley/konveyor-lib-ui#some-branch` as the version in package.json, and it will automatically build the `dist` for the library from the specified GitHub source. That way we can develop a PR in lib-ui and a PR in virt-ui that depends on it at the same time.
=> feat(package.json): add prepare script to package.json which should run when installing from github

src/hooks/useFormState/useFormState.ts
Addresses I'm seeing in https://github.com/konveyor/virt-ui/pull/189. To verify the fix you can test it alongside that PR by checking out these branches in both repos and using the `yarn link` instructions I added to this repo's README.
Basically, the plan wizard has to wait for some queries to resolve before it can pre-fill the form values for editing a plan, and in the case where those queries are already cached that means the prefill will happen immediately after the first render but asynchronously (since it waits for the cache to resolve). It happens so fast that `useFormState` is still performing its initial validation when the new values are set. Since validation is asynchronous, there was a race condition where validation A could start, then validation B could start, but if B …
=> fix(useformstate): fix race condition: only save validation if it's from the latest set of values

.github/workflows/test-and-release.yaml
Resolves https://github.com/konveyor/lib-ui/issues/34
See the error in this action run: https://github.com/konveyor/lib-ui/runs/1657087562?check_suite_focus=true
=> fix(ci): upgrade GitHub Pages deploy action to address deprecated set-env command

.github/workflows/test-and-release.yaml, .github/workflows/tests-ci.yaml, .releaserc, .storybook/helpers/GithubLink.tsx, .storybook/theme.js, README.md, package.json
Needed to fix CI and semantic-release
=> ci(main): rename master to main in workflow files, storybook files and README

src/components/StatusIcon/StatusIcon.stories.mdx, src/components/StatusIcon/StatusIcon.test.tsx, src/components/StatusIcon/StatusIcon.tsx
BREAKING CHANGE: `statusType` prop of the `StatusIcon` component is now a string, and the `StatusType` enum is no longer exported.
Replaces string enums with unions types.
Use lookup table for icons.  
https://github.com/konveyor/lib-ui/issues/48
=> feat(StatusIcon): Declarative approach using union types

src/components/StatusIcon/StatusIcon.stories.mdx, src/components/StatusIcon/StatusIcon.test.tsx, src/components/StatusIcon/StatusIcon.tsx
Needed for https://github.com/konveyor/forklift-ui/pull/440
For now, hard-codes the default color for icons to `#151515` which is the PatternFly `--pf-global--Color--100`. I didn't use the actual variable because for some reason it was resolving to `#000`, which appears to be fixed in a newer PF version. Should be fixed by a future version update (https://github.com/konveyor/lib-ui/issues/52).
=> feat(statusicon): add Paused status type to StatusIcon

src/hooks/useFormState/useFormState.ts
I screwed up in #57.
useFormState and useFormField now require `yup.AnySchema<T>` schema types instead of the `yup.SchemaOf<T>` which was not behaving correctly with boolean fields.
=> fix(useformstate): hotfix: we needed AnySchema<T> instead of SchemaOf<T> for the yup breaking change

src/hooks/useFormState/useFormState.stories.mdx, src/hooks/useFormState/useFormState.stories.tsx, src/hooks/useFormState/useFormState.ts, tsconfig.json
Also adds a "Complex field types and validations" example to the docs.
After #59, I realized that a schema e.g. `yup.mixed<T>()` would cause TypeScript to infer the field type as `T | undefined`. This is especially annoying for things like arrays where it would expect every element to be possibly undefined. To prevent ripple effects on all form code that previously assumed field values are always defined unless specified otherwise, I changed the type annotations on `useFormField` such that `T` will always be inferred as a defined value.
The side effect of this is that it is now invalid to allow undefined field values in `useFormState`, but that is an antipattern anyway, because null should be used for intentionally blank fields.
Required for an upcoming forklift-ui PR.
=> fix(useformstate): properly assert that field types inferred from yup schema are defined

src/hooks/useFormState/useFormState.stories.mdx, src/hooks/useFormState/useFormState.stories.tsx, src/hooks/useFormState/useFormState.ts
Needed for https://github.com/konveyor/forklift-ui/issues/625, see the description there for more context.
Currently, we have a `setInitialValue` function that changes a field's `initializedValue`, which is used to determine the field's `isDirty` property (whether it differs from the current value) and is used when calling `reset()`.
The problem is, in the PlanWizard in forklift-ui we want to be able to prefill values asynchronously (currently using `setInitialValue`) and retain that behavior of `isDirty` being false if the values still match the prefilled values (so we don't get an enabled Next/Submit button until the user actually changes something), but also have the ability to clear the form to empty values rather than the prefilled ones. (necessary when the user changes provider …
=> feat(useformstate): replace setInitialValue/reset with prefill/revert and reinitialize/clear

.github/workflows/test-and-release.yaml, README.md
Our Storybook docs were originally deployed to konveyor.github.io/lib-ui, which now redirects to konveyor.io/lib-ui. This worked for a while, but has since become a 404 now that the new konveyor.io website has been published.
We could figure this out and restore the usage of either konveyor.io or github.io later, but the audience for these docs is internal and small and I don't think it's necessarily worth the effort. This PR gets our docs back online by moving our main Storybook deployment to Surge, like our PR previews. The new URL is http://konveyor-lib-ui.surge.sh/.
=> docs(storybook): switch Storybook deployment from GitHub Pages to Surge to avoid DNS issues

.github/workflows/test-and-release.yaml, README.md
Reverts konveyor/lib-ui#70
konveyor.github.io/lib-ui is no longer redirecting to konveyor.io, so I think if we want we could restore this to GitHub Pages instead of using Surge.
=> Revert "docs(storybook): switch Storybook deployment from GitHub Pages to Surge to avoid DNS issues"

src/components/ValidatedTextInput/ValidatedTextInput.tsx, src/hooks/useFormState/useFormState.stories.mdx, src/hooks/useFormState/useFormState.stories.tsx, src/hooks/useFormState/useFormState.ts
Previously the field-level `isValid` property would be true on first render and only accurately reflect the validation after `isTouched` becomes true (the user blurred the field, in most cases). This is misleading and can lead to issues. `isValid` will now always accurately reflect the validation, so it will be false on first render if a required text field is blank. Consumers should now only show errors on a field if both `isValid` is false and `isTouched` is true. The new property `field.shouldShowError` has been added as a shorthand for this.
Also, a new parameter `greenWhenValid` has been added to `ValidatedTextInput` and the `get*Props` helpers. This is useful for fields with asynchronous validation that should show a green check when the field is valid, using the …
=> feat(useformstate): change `field.isValid` to ignore `isTouched`, add `shouldShowError` + `greenWhenValid`

src/hooks/useFormState/useFormState.stories.mdx, src/hooks/useFormState/useFormState.ts
See updated comments on the prop interfaces. `markSaved` is useful to set all fields as clean
after saving form values to storage, so that revert() will restore those values.
Other new methods apply the existing field-level methods to multiple fields at once.
Needed for https://github.com/konveyor/crane-ui-plugin/pull/17
=> feat(useformstate): add `markSaved` and other methods for manipulating multiple form fields at once

src/components/ValidatedTextInput/ValidatedTextInput.tsx
If the yup schema of a text field contains a `.label()` (needed for good error messages), `ValidatedTextInput` will use it as a default for the `label` prop so the consumer doesn't have to duplicate it.
=> feat(ValidatedTextInput): default field label to label defined in schema if present

src/components/ValidatedTextInput/ValidatedPasswordInput.tsx, src/components/ValidatedTextInput/ValidatedTextInput.tsx, src/hooks/useFormState/useFormState.ts
Allows passing an extra onBlur handler to ValidatedTextInput and ValidatedPasswordInput, and to facilitate it, refactors getFormGroupProps and getTextInputProps to take an object of options including the existing greenWhenValid and the new onBlur (to avoid piling on unnamed params)
BREAKING CHANGE: Any direct calls to getTextInputProps or getFormGroupProps that were passing a boolean for greenWhenValid will now need to instead pass an options object including greenWhenValid as a property.
To help with https://github.com/konveyor/crane-ui-plugin/pull/23
=> feat(ValidatedTextInput): add onBlur prop and refactor helpers to use options objects

src/hooks/useFormState/useFormState.stories.mdx, src/hooks/useFormState/useFormState.ts
Replaces the `yupOptions` argument with an options object including `yupOptions` and a new option called `revalidateOnChange`, which is an array of arbitrary variables. If any of these variables changed since the last validation, the form will revalidate even if none of the field values changed. This can be used to force revalidation when some asynchronous task is done, like checking a connection from credentials stored in form state.
BREAKING CHANGE: Any forms using the `yupOptions` argument will need to wrap it in an object with the property `yupOptions` instead of passing it directly as a top-level argument.
Needed for https://github.com/konveyor/crane-ui-plugin/pull/23
=> feat(useFormState): add `revalidateOnChange` dependencies array option, refactor options into object

src/components/ValidatedTextInput/ValidatedPasswordInput.tsx
Replicate behavior of https://github.com/konveyor/lib-ui/pull/85 for ValidatedPasswordInput
=> fix(ValidatedPasswordInput): default to label from field schema (match ValidatedTextInput behavior)

src/modules/kube-client/resources/core.ts
The kube-client module was originally abstracted out from mig-ui and still only directly supported the resource `kind`s needed by that UI.
In forklift-ui, we created our own `ForkliftResource` class to solve this problem, but that isn't really necessary when we're just trying to load core resources that aren't explicitly listed in the enums here, so we should just allow any string for the kind.
Needed for https://github.com/konveyor/crane-ui-plugin/pull/23
=> feat(kube-client): allow arbitrary strings for the `kind` property on resources being queried

package.json, src/hooks/useLocalStorage/index.ts, src/hooks/useLocalStorage/useLocalStorage.stories.mdx, src/hooks/useLocalStorage/useLocalStorage.stories.tsx, src/hooks/useLocalStorage/useLocalStorage.ts, src/index.ts, yarn.lock
This PR adds the `useLocalStorage` hook, based on [the implementation in crane-ui-plugin here](https://github.com/konveyor/crane-ui-plugin/blob/main/src/common/hooks/useLocalStorage.ts), which is itself a simplification of the `LocalStorageContext` from forklift-ui [here](https://github.com/konveyor/forklift-ui/blob/main/pkg/web/src/app/common/context/LocalStorageContext.tsx).
It has been enhanced since the crane-ui-plugin version to use `JSON.stringify()` and TypeScript generics so that any JSON-serializable value can be persistent instead of just strings. It also has error handling added and the addition of a check for `window` to be defined so that it won't break components in a server-rendering or unit testing environment.
I also upgraded `tslib` as part of this PR so we can use …
=> feat(hooks): Add useLocalStorage hook and documentation

.storybook/helpers/PackageMovedAlert.tsx, README.md, src/common/packageMovedConsoleWarning.ts, src/components/StatusIcon/StatusIcon.stories.mdx, src/components/ValidatedTextInput/ValidatedTextInput.stories.mdx, src/hooks/useFormState/useFormState.stories.mdx, src/hooks/useLocalStorage/useLocalStorage.stories.mdx, src/hooks/useSelectionState/useSelectionState.stories.mdx, src/index.ts, src/modules/kube-client/index.ts
Adds console warnings and an Alert at the top of every Storybook docs page regarding the move to the `@migtools/lib-ui` package name.
In the console:
In Storybook:
=> feat(index): Add warnings about moving package to `@migtools/lib-ui`

src/hooks/useSelectionState/useSelectionState.stories.mdx, src/hooks/useSelectionState/useSelectionState.stories.tsx, src/hooks/useSelectionState/useSelectionState.ts
See explanation around the new example in Storybook documentation.
This PR also attempts to memoize things in `useSelectionState` as much as possible since `.filter()` is called on each render in two places now. Note that this will only help if the consumer passes in stable functions for `isEqual` and `isItemSelectable`, which this example currently doesn't (because it is cumbersome -- you need to use `useCallback` or define the function outside your component). However, these optimizations are unnecessary unless the consumer has a very large number of items. The memoization added in this PR is simply there so that it is possible for the consumer to leverage it if they need to.
We should add explanations in JSDoc/TSDoc comments or some other means where the user can see it via …
=> feat(useSelectionState): add `isItemSelectable` option

package.json, src/common/types.ts, src/components/ResolvedQuery/ResolvedQueries.tsx, src/queries/helpers.ts, yarn.lock
Following the guide at https://tanstack.com/query/v4/docs/react/guides/migrating-to-react-query-4.
Not much needed to change here:
* Package name in imports
* Removal of `isIdle` state since it has been removed from react-query
* This results in ResolvedQueries rendering a loading spinner while a query is idle instead of rendering the children with no data. I don't think this breaks us, but we can reevaluate after testing it in Tackle.
=> build(package.json): Upgrade react-query to v4

package.json, src/components/LabelCustomColor/LabelCustomColor.stories.mdx, src/components/LabelCustomColor/LabelCustomColor.stories.tsx, src/components/LabelCustomColor/LabelCustomColor.tsx, src/components/LabelCustomColor/index.ts, src/index.ts, yarn.lock
Adds a LabelCustomColor component which attempts to render a PatternFly Label with any given hex color, adjusting colors to maintain acceptable text/background contrast.
Idea: If we have a defined set of colors for Tackle Hub, we could write unit tests here that render labels in every one of those colors and check the contrast with real a11y validators like axe.
=> feat: Add LabelCustomColor component

src/components/LabelCustomColor/LabelCustomColor.stories.tsx
After examining the existing tag editor code that uses these global palette tokens, I figured we should try to stick to them for the closest matching colors in our example color set.
=> docs(LabelCustomColor): Align example colors with PF colors where possible

src/hooks/useStorage/useLocalStorage.stories.mdx, src/hooks/useStorage/useLocalStorage.stories.tsx, src/hooks/useStorage/useSessionStorage.stories.mdx, src/hooks/useStorage/useSessionStorage.stories.tsx, src/hooks/useStorage/useStorage.ts
BREAKING CHANGE: useLocalStorage and useSessionStorage (via useStorage) require an object of named options instead of multiple function arguments
To support https://github.com/konveyor/tackle2-ui/pull/1355. I am refactoring a hook that calls multiple state source hooks and needs to be able to disable all but the currently used one. Adding a third/fourth function argument to these hooks seemed to making things less readable, so I refactored these hooks to take objects of named options for readability.
=> feat(useStorage): Add isEnabled option to useStorage/useLocalStorage/useSessionStorage via refactor to use options objects
